### ISSUE TITLE
using 8u212_2.12.8_1.2.8 fails with Permission denied

### ISSUE THREAD

**Issue by robstoll** [hseeberger/scala-sbt#74]
I get the following exception:
```
java.io.FileNotFoundException: /builds/tegonal/scala-steward/sbt-cache/boot/sbt.boot.lock (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```
Using 8u181_2.12.8_1.2.8 in the same setup works

**Comment by hseeberger** [comment]
How are you starting the container?

**Comment by hseeberger** [comment]
Please use 8u212_1.2.8_2.12.8, not 8u212_2.12.8_1.2.8.
